### Create new contribution
POST http://localhost:8080/contributions?username=dirk
Content-Type: application/json

{
    "spans": [
        {
            "type": "STYLED_TEXT",
            "text": "Hello World!\n",
            "bold": true
        },
        {
            "type": "TAG",
            "tagName": "hdp"
        }
    ]
}

> {%
    client.global.set("contribution_id", response.body)
%}

### Get the new contribution
GET http://localhost:8080/contributions/{{ contribution_id }}

### Like the contribution
POST http://localhost:8080/contributions/{{ contribution_id }}/like?username=jelmer

### Reply to the contribution
POST http://localhost:8080/contributions/{{ contribution_id }}/reply?username=koen
Content-Type: application/json

{
    "spans": [
        {
            "type": "STYLED_TEXT",
            "text": "Hello "
        },
        {
            "type": "MENTION",
            "username": "dirk"
        }
    ]
}

> {% client.global.set("reply_id", response.body) %}

### Like the reply
POST http://localhost:8080/contributions/{{ contribution_id }}/replies/{{ reply_id }}/like?username=dirk
